/*
 * This file is part of the Whisper Protocol distributed at https://github.com/NodleCode/whisper-tracing-android
 * Copyright (C) 2020  Coalition Network
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package world.coalition.whisper.id

/**
 * @author Lucien Loiseau on 09/04/20.
 */
data class ProofOfInteraction(
    val tellToken: ByteArray,
    val hearToken: ByteArray) {

    // generated by android studio
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ProofOfInteraction

        if (!tellToken.contentEquals(other.tellToken)) return false
        if (!hearToken.contentEquals(other.hearToken)) return false

        return true
    }

    // generated by android studio
    override fun hashCode(): Int {
        var result = tellToken.contentHashCode()
        result = 31 * result + hearToken.contentHashCode()
        return result
    }
}